# Generated by Django 6.0.8 on 2026-08-06 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('github', 'GitHub'), ('iafrica', 'iAfrica')], max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('language', 'Language'), ('framework', 'Framework'), ('tool', 'Tool')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HypeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mentions_count', models.IntegerField()),
                ('source', models.CharField(default='github', max_length=50)),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hype_snapshots', to='tracker.technology')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('technology', 'date', 'source'), name='unique_hype_snapshot_per_day')],
            },
        ),
        migrations.CreateModel(
            name='DemandSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('job_mentions_count', models.IntegerField()),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(default='iafrica', max_length=50)),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_snapshots', to='tracker.technology')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('technology', 'date', 'source'), name='unique_demand_snapshot_per_day')],
            },
        ),
    ]
